import { sqliteTable, text, integer, numeric, real } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

// Users table (mirrors auth.users from Supabase/PostgreSQL)
export const users = sqliteTable('users', {
  id: text('id').primaryKey(), // UUID generated by app
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
});

// Profiles
export const profiles = sqliteTable('profiles', {
  id: text('id').primaryKey().references(() => users.id, { onDelete: 'cascade' }),
  email: text('email').notNull().unique(),
  fullName: text('full_name').notNull(),
  role: text('role', { enum: ['customer', 'employee', 'admin', 'courier'] }).default('customer').notNull(),
  avatarUrl: text('avatar_url'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
});

// Materials
export const materials = sqliteTable('materials', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  type: text('type', { enum: ['ink', 'substrate', 'frame', 'coating'] }).notNull(),
  basePriceEgp: real('base_price_egp').notNull(), // SQLite uses REAL for numeric/floats
  stockLevel: real('stock_level').notNull().default(0),
  stockUnit: text('stock_unit').notNull(),
  isAvailable: integer('is_available', { mode: 'boolean' }).default(true).notNull(),
  updatedBy: text('updated_by').references(() => profiles.id),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
});

// Promo Codes
export const promoCodes = sqliteTable('promo_codes', {
  id: text('id').primaryKey(),
  code: text('code').notNull().unique(),
  discountPercentage: real('discount_percentage').notNull(),
  maxDiscountEgp: real('max_discount_egp'),
  validFrom: text('valid_from').notNull(),
  validUntil: text('valid_until').notNull(),
  usageLimit: integer('usage_limit'),
  usageCount: integer('usage_count').default(0).notNull(),
  isActive: integer('is_active', { mode: 'boolean' }).default(true).notNull(),
  updatedBy: text('updated_by').references(() => profiles.id),
});

// Orders
export const orders = sqliteTable('orders', {
  id: text('id').primaryKey(),
  idempotencyKey: text('idempotency_key').notNull().unique(), // CRITICAL: Ensures queue processes once
  customerId: text('customer_id').notNull().references(() => profiles.id),
  employeeId: text('employee_id').references(() => profiles.id),
  courierId: text('courier_id').references(() => profiles.id),
  status: text('status', { enum: ['pending', 'processing', 'quality_check', 'ready', 'in_transit', 'delivered', 'cancelled'] }).default('pending').notNull(),
  
  // Dimensions and file
  widthCm: real('width_cm').notNull(),
  heightCm: real('height_cm').notNull(),
  fileUrl: text('file_url').notNull(), // Will point to R2 presigned read URL
  
  // High-End Print Quality Metadata (Extracted by Queue Worker)
  dpi: integer('dpi'),
  colorSpace: text('color_space'),
  printWidthPx: integer('print_width_px'),
  printHeightPx: integer('print_height_px'),

  // Material relations
  substrateMaterialId: text('substrate_material_id').notNull().references(() => materials.id),
  frameMaterialId: text('frame_material_id').references(() => materials.id),
  coatingMaterialId: text('coating_material_id').references(() => materials.id),
  
  complexityScore: real('complexity_score').default(1.0).notNull(),
  promoCodeId: text('promo_code_id').references(() => promoCodes.id),
  
  priceEgp: real('price_egp').notNull(),
  discountAppliedEgp: real('discount_applied_egp').default(0).notNull(),
  priceBreakdown: text('price_breakdown', { mode: 'json' }).notNull().default('{}'),
  
  shippingAddress: text('shipping_address').notNull(),
  deliveryCoords: text('delivery_coords', { mode: 'json' }),
  
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
});

// System Config
export const systemConfig = sqliteTable('system_config', {
  key: text('key').primaryKey(),
  value: text('value', { mode: 'json' }).notNull(),
  updatedBy: text('updated_by').references(() => profiles.id),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
});
